services:
  postgres:
    image: postgres:18
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:8.2.2
    container_name: redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - cache:/data
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    env_file:
      - .env
    volumes:
      - queue:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672" # COMMUNICATION
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # WEB UI

  seq:
    image: datalust/seq:2025
    container_name: seq
    env_file:
      - .env
    ports:
      - "${SEQ_PORT}:5341" # COMMUNICATION
      - "${SEQ_WEB_PORT}:80" # WEB UI
    volumes:
      - log:/data

volumes:
  db:
  cache:
  queue:
  log:
