services:
  postgres:
    image: postgres:18
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    image: redis:8.2.2
    container_name: redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    env_file:
      - .env
    volumes:
      - queue:/var/lib/rabbitmq
    ports:
      - "5672:5672" # COMMUNICATION
      - "15672:15672" # WEB UI
  seq:
    image: datalust/seq:2025
    container_name: seq
    env_file:
      - .env
    ports:
      - "5341:5341" # COMMUNICATION
      - "5342:80" # WEB UI
    volumes:
      - log:/data
volumes:
  db:
  cache:
  queue:
  log:
